### ISSUE TITLE
Epic: Library/framework integrations

### ISSUE THREAD

**Issue by jhawthorn** [jhawthorn/vernier#34]
One cool feature of Vernier (and the firefox profiler we use as a viewer) is that it supports tracing via "markers", which record events which happened during the profile.

![](https://user-images.githubusercontent.com/131752/263089805-6d2c5492-da00-45a5-b46d-1c2372865fea.png)

When Aaron and I showcased Vernier, we cheated (slightly) and added some small hooks to trace Rails and Sidekiq. I do something pretty similar in `examples/rails.rb`.

``` ruby
Vernier.trace(out: "rails.json") do |collector|
  ActiveSupport::Notifications.monotonic_subscribe do |name, start, finish, id, payload|
    collector.add_marker(
      name:,
      start: (start * 1_000_000_000).to_i,
      finish: (finish * 1_000_000_000).to_i,
    )
  end
```

That's simple enough, it subscribes to every `ActiveSupport::Notifications` topic and forwards them, but it doesn't provide as much information as it could and it doesn't happen by default.

Let's do this better and automatically detect and instrumenting popular libraries!

```[tasklist]
- [x] Detect Rails and install the subscriber above
- [ ] Detect Sidekiq and install instrumentation
- [ ] Add configuration for enabling/disabling these integrations
- [x] Add more details to the markers by adding to the "marker schema"
- [x] Disable integrations when profiling ends
- [ ] Figure out if there's a way to detect Rails/sidekiq/whatever being loaded _after_ the profile starts
```

**Comment by PedroAugustoRamalhoDuarte** [comment]
@jhawthorn thanks for this awesome library. I search I little bit and I cannot find an easy way to set up vernier with rails.

I saw the example with the minimal app, and it's working great, but how I can achieve that with a conventional rails app?

**Comment by benoittgt** [comment]
@PedroAugustoRamalhoDuarte I know it's not shortest answer but I recommend looking at https://youtu.be/9nvX3OHykGQ
